### ISSUE TITLE
win32 + msvc12: 5.22 installation issues

### ISSUE THREAD

**Issue by sten22** [perl11/cperl#195]
I'm trying build 5.22.4c from sources:
1: after `nmake install` no perl.exe nor cperl.exe in bin folder, I have to copy it manualy from source folder

2: several failed tests:

```
Test Summary Report
-------------------
io/utf8.t                                                       (Wstat: 0 Tests:
 63 Failed: 1)
  Failed test:  28
porting/pod_rules.t                                             (Wstat: 0 Tests:
 7 Failed: 1)
  Failed test:  4
porting/regen.t                                                 (Wstat: 65280 Te
sts: 10 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
../cpan/B-C/t/e_perlcc.t                                        (Wstat: 1280 Tes
ts: 87 Failed: 5)
  Failed tests:  12-14, 17-18
  TODO passed:   22
  Non-zero exit status: 5
../cpan/B-C/t/stash.t                                           (Wstat: 0 Tests:
 4 Failed: 0)
  TODO passed:   4
../dist/Net-Ping/t/001_new.t                                    (Wstat: 65280 Te
sts: 9 Failed: 0)
  Non-zero exit status: 255
../ext/B/t/sv_stash.t                                           (Wstat: 0 Tests:
 1 Failed: 0)
  TODO passed:   1
../ext/File-Find/t/find.t                                       (Wstat: 3328 Tes
ts: 123 Failed: 0)
  Non-zero exit status: 13
  Parse errors: Bad plan.  You planned 135 tests but ran 123.
../lib/File/Copy.t                                              (Wstat: 256 Test
s: 466 Failed: 1)
  Failed test:  53
  Non-zero exit status: 1
../lib/locale.t                                                 (Wstat: 0 Tests:
 660 Failed: 1)
  Failed test:  424
Files=2536, Tests=714242, 1210 wallclock secs (62.23 usr +  5.78 sys = 68.02 CPU
)
Result: FAIL
NMAKE : fatal error U1077: '.\perl.exe' : return code '0x9'
Stop.
```

3: no cperl.lib in CORE, just try install any XS:
`NMAKE : fatal error U1073: don't know how to make 'C:\cperl\lib\CORE\cperl522.lib'`
need to manualy copy it from source folder

**Comment by rurban** [comment]
Can you test `smoke/maint-5.24c` or `smoke/master`? 
This should fix it. I did the exe part a bit different, but thanks for the PR.

I have not updated maint-5.22.c yet. I'm far behind there. The commit can be easily backported but I wanted to keep them in order, and there's so much more missing.

**Comment by rurban** [comment]
Closing. Will be cherry-picked to maint-5.22.c later, with all the other backports.

**Comment by sten22** [comment]
Just tried smoke/maint-5.24c and got few test errors:

```
Test Summary Report
-------------------
porting/pending-author.t                                        (Wstat: 0 Tests:
 1 Failed: 1)
  Failed test:  1
../cpan/Archive-Tar/t/09_roundtrip.t                            (Wstat: 0 Tests:
 7 Failed: 0)
  TODO passed:   1, 4, 6
../cpan/B-C/t/e_perlcc.t                                        (Wstat: 0 Tests:
 87 Failed: 0)
  TODO passed:   22, 41-43
../cpan/B-C/t/modules.t                                         (Wstat: 0 Tests:
 40 Failed: 0)
  TODO passed:   5-6, 8
../cpan/B-C/t/stash.t                                           (Wstat: 0 Tests:
 4 Failed: 0)
  TODO passed:   4
../cpan/IPC-Cmd/t/01_IPC-Cmd.t                                  (Wstat: 256 Test
s: 20 Failed: 0)
  Non-zero exit status: 1
  Parse errors: No plan found in TAP output
../dist/ExtUtils-CBuilder/t/00-have-compiler.t                  (Wstat: 256 Test
s: 2 Failed: 0)
  Non-zero exit status: 1
  Parse errors: Bad plan.  You planned 7 tests but ran 2.
../ext/File-Find/t/find.t                                       (Wstat: 3328 Tes
ts: 125 Failed: 0)
  Non-zero exit status: 13
  Parse errors: Bad plan.  You planned 137 tests but ran 125.
../lib/File/Copy.t                                              (Wstat: 256 Test
s: 466 Failed: 1)
  Failed test:  53
  Non-zero exit status: 1
Files=2581, Tests=842389, 28715 wallclock secs (90.64 usr +  7.95 sys = 98.59 CP
U)
Result: FAIL
NMAKE : fatal error U1077: '.\perl.exe' : return code '0x2'
Stop.
```

B::C tests shows Windows exception window
IPC::Cmd and ExtUtils::CBuilder stuck and I had to kill perl.exe manualy in task manager

**Comment by rurban** [comment]
Is the installation issue fixed? The others are not so problematic. Our own MSVC10+12 smokers works fine on these, both 32+64bit.

**Comment by sten22** [comment]
Yes, installation issues is fixed(1 and 3).

Regarding to tests, I've compared them with your appveyor - B-C/t/modules.t is skipped. Other tests may fail due to windows locale. Do you have any plans to fix the support of B::C compiler for win32?

**Comment by rurban** [comment]
Sure. B-C is still in work for 5.24. See also https://github.com/CpanelInc/perl-compiler for a limited version with support for only version and OS, and various new ideas.
COW support is still not satisfying.

**Comment by sten22** [comment]
Thanks, I already follow to CpanelInc/perl-compiler, but seems that win32 support were completely removed from bc524 branch
